### PR TITLE
Update Handbrake to 1.x

### PR DESCRIPTION
**Pull request by homerjam**
Hi,

I've followed the instructions in #23 and everything is fine on mac. Are you able to test on windows?

I should be able to test on linux using docker at some point.

Hope everything looks ok - let me know any changes!

Thanks

### CODE REVIEW

**Comment by 75lb** [comment]
hi, thanks! I will review this ASAP - today, hopefully.

**Comment by 75lb** [comment]
looks good so far, thanks. Could you run the test suite on Linux please? I'll test on Windows.

**Comment by homerjam** [comment]
I've tested on ubuntu 16.04 via docker, all tests pass!

**Comment by 75lb** [comment]
merged into `master` and released in v3.0.0. Thanks mate 👍

**Comment by homerjam** [comment]
Awesome, thanks!

**Pull request closed without merging**
