### PR TITLE
to Handbrake version 0.10.2

### PR DESCRIPTION
**Pull request by aschmid**
handbrake link to 0.10.1 does not work any more.

### CODE REVIEW

**Comment by 75lb** [comment]
cheers bro, merged and released :+1:

**Comment by 75lb** [comment]
fyi, you didn't commit using a registered github email so you don't show up in the contributor list.. if you add this email to your account as an alternative address, you should show up..

**Comment by aschmid** [comment]
what email do you see in the commit?

**Comment by aschmid** [comment]
ok got it. i added the email address now.

**Pull request merged**
