### PR TITLE
Patch for equals signs on CLI params (issue #16)

### PR DESCRIPTION
**Pull request by horsepress**
As per issue #16 (CLI options requiring equals sign not passed correctly), I've added code in handbrake.js to handle the use of parameters like ```--rotate=4``` , where an equals sign is required. ```object-to-spawn-arg``` doesn't handle this behaviour, which is peculiar to Handbrake (I think because it allows defaulting of options - e.g. ```--rotate``` is the same as ```--rotate=3```)

I've flagged the options that need this treatment in cli-options.js. I've not checked thoroughly which options need to be handled in this way: I've just done the ones that I use. Just add ```needsEqualsSign:true```  ```useQuotesAroundValue:true``` to options to enable the necessary behaviour. Strings will default to using quotes unless the option is set to false. 

The values passed should be escaped for quotes if quotes or used.... I haven't implemented: not sure on best approach for cross-platform compatibility.

### CODE REVIEW

**Comment by 75lb** [comment]
great, thanks.. will take a look now.

**Comment by 75lb** [comment]
everything seems to work well, thanks! my only question is, do we need `needsEqualsSign:true` on `markers` as it is a boolean option.. it doesn't accept a value.. 
```
{ name: 'markers', type: Boolean, alias: 'm', group: 'destination', needsEqualsSign:true, useQuotesAroundValue:true },
```

**Comment by 75lb** [comment]
should `{ markers: true }` be converted to `{ 'markers="true": '' }` ?

**Comment by horsepress** [comment]
Thanks.

For markers, see https://trac.handbrake.fr/wiki/CLIGuide under "destination options":

> -m or --markers: this setting includes a chapter index in the video, based on the chapter times used in the source. In .mp4 files, these chapter markers are in QuickTime's format. They can be read by VLC, QuickTime, iTunes, the AppleTV, the iPod, and the iPhone. In order for QuickTime to see the chapters, you must rename the output file to end with .m4v instead of .mp4.
> If you wish to import chapter names from a csv file, you can do so using the following: --markers="/full/path/to/chapters_file.csv" The CSV file should be formatted as follows:

So if it's a boolean, no quotes or equals sign. this should be handled by the code because strictly true values are excluded, but if a string (i.e. csv file) is passed should be ok.

I also wondered if it would be better to make a new modified options object rather than to update the existing options object... I'm not sure if it might get reused later (e.g. to alter settings for a subsequent run). Let me know what you think.

Also might be clearer to rename "useQuotesAroundValue" to "useQuotesAroundValueFollowingEqualsSign" for clarity, since it has no effect unless the equals sign is on.

**Comment by 75lb** [comment]
ok, thanks.. good shout about the options clone - implemented.. i didn't change the property name as i think you explained it enough in the `patchOptions` comments.. 

could you take a look and check the tests i added are sufficient.. if so, i'll release it.

**Pull request merged**
